import {ChevronLeft,ChevronRight,FileSpreadsheet,FileText,Pin} from 'lucide-react';
import {useEffect,useMemo,useRef,useState} from 'react';
import type {DocumentItem} from '../../types';
import {DragDropZone} from '../ui/DragDropZone';import {SkeletonList} from '../ui/Skeleton';
const MIN=56,DEFAULT=320;
export function ResizableFilesPanel({documents,active,onSelect,onUpload,containerRef,loading=false}:{documents:DocumentItem[];active:string;onSelect:(id:string)=>void;onUpload:(file:File)=>void;containerRef:React.RefObject<HTMLElement|null>;loading?:boolean}){
 const [width,setWidth]=useState(DEFAULT),[dragging,setDragging]=useState(false),[type,setType]=useState('all'),[filiale,setFiliale]=useState('all'),[application,setApplication]=useState('all');const [pinned,setPinned]=useState<string[]>(()=>JSON.parse(localStorage.getItem('cb-pinned-files')??'[]'));const input=useRef<HTMLInputElement>(null),collapsed=width<=MIN+20;
 useEffect(()=>{if(!dragging)return;const move=(e:MouseEvent)=>{const rect=containerRef.current?.getBoundingClientRect();if(rect)setWidth(Math.max(MIN,Math.min(rect.width*.5,rect.right-e.clientX)))};const up=()=>setDragging(false);addEventListener('mousemove',move);addEventListener('mouseup',up);return()=>{removeEventListener('mousemove',move);removeEventListener('mouseup',up)}},[dragging,containerRef]);
 const visible=useMemo(()=>documents.filter(d=>(type==='all'||type==='pinned'&&pinned.includes(d.id)||type==='pdf'&&d.type==='pdf'||type==='doc'&&['doc','docx'].includes(d.type))&&(filiale==='all'||d.filiale===filiale)&&(application==='all'||d.application===application)),[documents,type,pinned,filiale,application]);
 function pin(id:string,e:React.MouseEvent){e.stopPropagation();setPinned(old=>{const next=old.includes(id)?old.filter(x=>x!==id):[...old,id];localStorage.setItem('cb-pinned-files',JSON.stringify(next));return next})}
 return <aside className={`files-panel glass-card${collapsed?' files-panel--collapsed':''}`} style={{width}}><input ref={input} hidden type="file" accept=".pdf,.docx,.doc,.xlsx,.csv,.zip" onChange={e=>{const f=e.target.files?.[0];if(f)onUpload(f);e.currentTarget.value=''}}/><div className="files-panel__resize" onMouseDown={()=>setDragging(true)}/><button className="files-panel__collapse" onClick={()=>setWidth(collapsed?DEFAULT:MIN)}>{collapsed?<ChevronLeft size={16}/>:<ChevronRight size={16}/>}</button>
 {!collapsed&&<><header className="files-panel__header"><h2>Documents <span>({documents.length})</span></h2></header><div className="document-scope-filters"><label>Filiale<select value={filiale} onChange={e=>setFiliale(e.target.value)}><option value="all">All</option>{['OCM','OEG','OJO','OCI'].map(v=><option key={v}>{v}</option>)}</select></label><label>Application<select value={application} onChange={e=>setApplication(e.target.value)}><option value="all">All</option>{['MZ','KPSA'].map(v=><option key={v}>{v}</option>)}</select></label></div><div className="filter-tabs">{[['all','All'],['pdf','PDFs'],['doc','Docs'],['pinned','Pinned']].map(([k,l])=><button key={k} className={type===k?'active':''} onClick={()=>setType(k)}>{l}</button>)}</div><div className="files-panel__list">{loading&&<SkeletonList count={3}/>} {!loading&&!documents.length&&<DragDropZone compact onFile={onUpload} label="Drag and drop files here or browse" sublabel="PDF, DOCX, XLSX, CSV"/>}{visible.map(doc=><button key={doc.id} className={`files-panel__item${active===doc.id?' active':''}`} onClick={()=>onSelect(doc.id)}><span className="files-panel__icon">{doc.type==='xlsx'?<FileSpreadsheet size={16}/>:<FileText size={16}/>}</span><span className="files-panel__meta"><strong>{doc.name}</strong><small>{doc.type.toUpperCase()} · {doc.blocks} blocks</small></span><span className={`files-panel__pin${pinned.includes(doc.id)?' pinned':''}`} onClick={e=>pin(doc.id,e)}><Pin size={14}/></span></button>)}</div></>}
 {collapsed&&<div className="files-panel__collapsed-icons"><button onClick={()=>input.current?.click()}><FileText size={18}/></button><span>{documents.length}</span></div>}</aside>
}
